// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const missingSupabaseEnv = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

if (missingSupabaseEnv) {
  console.error('Supabase env vars manquantes : VITE_SUPABASE_URL et VITE_SUPABASE_PUBLISHABLE_KEY doivent être définies.');
}

const createSupabaseClient = (): SupabaseClient<Database> | null => {
  if (missingSupabaseEnv) {
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createSupabaseClient();
export const supabaseConfigError = missingSupabaseEnv
  ? 'Configuration Supabase manquante. Définissez VITE_SUPABASE_URL et VITE_SUPABASE_PUBLISHABLE_KEY.'
  : null;
